### ISSUE TITLE
crash when using progressive S-mods

### ISSUE THREAD

**Issue by MoonshineBrew** [Alaricdragon/AIRetrofits#24]
How to recreate:
1. Open the progressive S-Mods menu
2. click "show all"
3. watch the game crash

Starsector Log:

1882818 [Thread-3] INFO  data.scripts.hullmods.AIRetrofit_AIretrofit  - Error: failed to get min crew in AIRetrofit hullmod. what were you even doing?
1882818 [Thread-3] INFO  sound.public  - Cleaning up music with id [miscallenous_corvus_campaign_music.ogg]
1882831 [Thread-7] INFO  sound.public  - Cleaning up music with id [faction_luddite_market_01_neutral_var01.ogg]
1883036 [Thread-10] INFO  sound.public  - Creating streaming player for music with id [faction_luddite_market_01_neutral_var01.ogg]
1883037 [Thread-10] INFO  sound.OooO  - Playing music with id [faction_luddite_market_01_neutral_var01.ogg]
1883152 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException
java.lang.NullPointerException
	at data.scripts.hullmods.AIRetrofit_AIretrofit.getUnapplicableReason(AIRetrofit_AIretrofit.java:302)
	at progsmod.data.campaign.rulecmd.ui.plugins.BuildInSelector.disableUnapplicable(BuildInSelector.java:130)
	at progsmod.data.campaign.rulecmd.ui.plugins.BuildInSelector.updateItems(BuildInSelector.java:69)
	at progsmod.data.campaign.rulecmd.ui.plugins.BuildInSelector.addNewItems(BuildInSelector.java:64)
	at progsmod.data.campaign.rulecmd.PSM_BuildInHullMod$1.showAllPressed(PSM_BuildInHullMod.java:163)
	at progsmod.data.campaign.rulecmd.ui.plugins.BuildInSelector.advance(BuildInSelector.java:167)
	at com.fs.starfarer.ui.newui.int.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.advance(Unknown Source)
	at com.fs.starfarer.ui.v.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.advance(Unknown Source)
	at com.fs.starfarer.E.I.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.advance(Unknown Source)
	at com.fs.starfarer.ui.v.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.N.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.advance(Unknown Source)
	at com.fs.starfarer.ui.newui.super.advance(Unknown Source)
	at com.fs.starfarer.ui.v.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.N.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.o0Oo.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.advance(Unknown Source)
	at com.fs.starfarer.ui.v.advanceImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)

**Comment by MoonshineBrew** [comment]
Only crashes when AI-Retrofit isn't equipped to the ship

**Comment by Alaricdragon** [comment]
i have just updated the mod, hopefully fixing it. i don't have mush time to test this though, so if you find any other bugs with progressive S-Mods or otherwise please inform me of them so i may fix them.
and thank you for the bug report.
